name: Build LaTeX document

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make_linux:
    name: Build with Makefile - Linux
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install LaTeX build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-fonts-extra

      - name: Run the Makefile
        run: |
          make all

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ROBERTO-PASTOR-CV-MAKEFILE-LINUX
          path: src/cv/out/ROBERTO-PASTOR.pdf
          retention-days: 7

  build_latex: 
    name: Build the LaTeX CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ROBERTO-PASTOR.tex
          working_directory: src/cv
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=out

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ROBERTO-PASTOR-CV
          path: src/cv/out/ROBERTO-PASTOR.pdf
          retention-days: 7

      - name: Deploy CV to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: src/cv/out
          clean: true
          clean-exclude: index.html
          single-commit: true

      - name: Create a CV release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./src/cv/out/ROBERTO-PASTOR.pdf
